force_drivers+=" t2bce_dma t2bce_core t2bce_vhci "
install_items+=" /etc/udev/rules.d/85-t2-network-unmanaged.rules "
install_items+=" /etc/vconsole.conf /usr/lib/kbd/consolefonts/latarcyrheb-sun32.psfu.gz "
