add_dracutmodules+=" systemd-resolved "
install_items+=" /etc/NetworkManager/conf.d/10-mdns.conf /etc/systemd/resolved.conf.d/10-mdns.conf "
install_optional_items+=" /usr/lib64/libnss_resolve.so.2 "
